import { ThreatAlert, MitreTechnique, DevelopmentModule, GanttWeek, GanttActivity } from '../types';

export const TEAM_MEMBERS = [
  { name: 'Jash Bharat Chothani', roll: 'B007' },
  { name: 'Shishir Jaimin Bhavsar', roll: 'B030' },
  { name: 'Ved Kantilal Waghela', roll: 'B061' },
];

export const PROJECT_DETAILS = {
  title: 'Kavach – AI-Driven SOAR-XDR Threat Intelligence & Response Platform',
  subtitle: 'Diploma Final Year Project in Computer Engineering (2026–2027)',
  institute: 'Shri Bhagubhai Mafatlal Polytechnic (Shri Vile Parle Kelavani Mandal\'s)',
  guide: 'Smt. Priti Bokariya',
  hod: 'Shri J. S. Kulkarni',
  sponsor: 'Swastik Chemical (India)',
  courseCode: 'PRO230812',
  semester: 'VI',
};

export const INITIAL_ALERTS: ThreatAlert[] = [
  {
    id: 'ALT-1001',
    timestamp: '2026-07-28 21:04:12',
    threatType: 'PowerShell Abuse',
    mitreId: 'T1059.001',
    severity: 'High',
    sourceLayer: 'Sysmon',
    target: 'DESKTOP-SW-04 (FINANCE)',
    detectionRule: 'Command line flagged for -enc, -nop, -w hidden, or IEX cradles.',
    automatedMitigation: 'Terminate the malicious PowerShell process automatically.',
    status: 'Contained',
    details: 'Detected obfuscated download cradle executing remote script payload from suspicious external IP.',
  },
  {
    id: 'ALT-1002',
    timestamp: '2026-07-28 20:45:30',
    threatType: 'Deepfake Voice/Video Impersonation',
    mitreId: 'T1656 / T1588.007',
    severity: 'Critical',
    sourceLayer: 'Deepfake/Vishing',
    target: 'CFO Video Call Session #492',
    detectionRule: 'AI model flags synthetic-audio spectral artefacts or facial-consistency anomalies.',
    automatedMitigation: 'Auto-terminate the session, alert SOC, and flag for mandatory manual verification.',
    status: 'Contained',
    details: 'Synthetic voice spectrum generated by GenAI detected during executive funds transfer conference call.',
  },
  {
    id: 'ALT-1003',
    timestamp: '2026-07-28 19:12:05',
    threatType: 'Ransomware Encryption',
    mitreId: 'T1486',
    severity: 'Critical',
    sourceLayer: 'Canary',
    target: 'FILESERVER-01 / Share / Finance',
    detectionRule: 'Canary file modified, or >10 file modifications detected within 30 seconds.',
    automatedMitigation: 'Ransomware playbook: immediate firewall block of all ingress/egress traffic.',
    status: 'Contained',
    details: 'Decoy canary file _Financial_Audit_2026.xlsx modified by suspicious process.',
  },
  {
    id: 'ALT-1004',
    timestamp: '2026-07-28 17:30:11',
    threatType: 'Brute-Force Attack',
    mitreId: 'T1110.001',
    severity: 'Medium',
    sourceLayer: 'Windows Event Log',
    target: 'DC-01 (Domain Controller)',
    detectionRule: 'More than 5 failed logon attempts from a remote IP within 10 minutes (Event ID 4625).',
    automatedMitigation: 'Disable the targeted user account automatically.',
    status: 'Contained',
    details: 'Repeated authentication failures against service account svc_backup from external gateway.',
  },
  {
    id: 'ALT-1005',
    timestamp: '2026-07-28 15:01:44',
    threatType: 'Vishing (Voice Phishing) Call',
    mitreId: 'T1598.004',
    severity: 'High',
    sourceLayer: 'Deepfake/Vishing',
    target: 'Procurement Desk Extension 412',
    detectionRule: 'Caller-ID cross-checked against directory; speech-pattern & urgency-language model flags scripts.',
    automatedMitigation: 'Auto-block/flag the caller, warn recipient in real time, and log incident.',
    status: 'Pending Approval',
    details: 'Inbound VoIP call claiming to be CEO demanding urgent wire transfer with high-urgency keywords.',
  },
];

export const MITRE_MATRIX: MitreTechnique[] = [
  {
    threatType: 'PowerShell Abuse',
    mitreId: 'T1059.001',
    category: 'Endpoint',
    detectionRule: 'Command line flagged for -enc, -nop, -w hidden, downloadstring, or IEX cradles.',
    automatedMitigation: 'Terminate the malicious PowerShell process automatically.',
  },
  {
    threatType: 'LSASS Memory Dump',
    mitreId: 'T1003.001',
    category: 'Endpoint',
    detectionRule: 'Sysmon Event ID 10 flags handles opened to lsass.exe with dangerous VM_READ access masks.',
    automatedMitigation: 'Isolate the host from the network and kill the dumping process.',
  },
  {
    threatType: 'Ransomware Encryption',
    mitreId: 'T1486',
    category: 'Endpoint',
    detectionRule: 'Canary file modified, or >10 file modifications detected within 30 seconds.',
    automatedMitigation: 'Ransomware playbook: immediate firewall block of all ingress/egress traffic.',
  },
  {
    threatType: 'Brute-Force Attack',
    mitreId: 'T1110.001',
    category: 'Endpoint',
    detectionRule: 'More than 5 failed logon attempts from a remote IP within 10 minutes.',
    automatedMitigation: 'Disable the targeted user account automatically.',
  },
  {
    threatType: 'Data Exfiltration',
    mitreId: 'T1048',
    category: 'Network',
    detectionRule: 'Outbound byte transfer exceeds the historical host baseline (z-score anomaly).',
    automatedMitigation: 'Alert the SOC via email/SMS and queue host isolation for analyst approval.',
  },
  {
    threatType: 'Malware Download',
    mitreId: 'T1105',
    category: 'Endpoint',
    detectionRule: 'SHA-256 hash of a newly created file matches the threat-intelligence blocklist.',
    automatedMitigation: 'Quarantine the file into an isolated storage location.',
  },
  {
    threatType: 'Deepfake Voice/Video Impersonation',
    mitreId: 'T1656 / T1588.007',
    category: 'Human Layer',
    detectionRule: 'AI model flags synthetic-audio spectral artefacts or facial-consistency anomalies during live call.',
    automatedMitigation: 'Auto-terminate the session, alert SOC, and flag the interaction for mandatory manual verification.',
  },
  {
    threatType: 'Vishing (Voice Phishing) Call',
    mitreId: 'T1598.004',
    category: 'Human Layer',
    detectionRule: 'Caller-ID cross-checked against directory; speech-pattern & urgency-language model flags social engineering scripts.',
    automatedMitigation: 'Auto-block/flag the caller, warn the recipient in real time, and log the incident for awareness training.',
  },
  {
    threatType: 'Phishing Website / Email',
    mitreId: 'T1566.002 / T1566',
    category: 'Human Layer',
    detectionRule: 'Real-time URL reputation + NLP content classifier detects lookalike domains, new SSL certs, and credential-harvesting forms.',
    automatedMitigation: 'Auto-block DNS resolution, quarantine the email, and submit a takedown request for the malicious URL.',
  },
];

export const DEVELOPMENT_MODULES: DevelopmentModule[] = [
  {
    number: 1,
    title: 'Requirement Gathering & Client Study',
    duration: 'Wk 1',
    dates: 'Jul 13–19, 2026',
    description: 'Study common attack techniques and map them to the MITRE ATT&CK framework.',
    keyTasks: [
      'Study common attack techniques and map them to MITRE ATT&CK.',
      'Understand Swastik Chemical (India)\'s live IT environment, endpoints, and threat exposure.'
    ]
  },
  {
    number: 2,
    title: 'System Design & Architecture Planning',
    duration: 'Wk 2',
    dates: 'Jul 20–26, 2026',
    description: 'Design end-to-end telemetry flow and database schema.',
    keyTasks: [
      'Design telemetry collection → detection → correlation → automated response pipeline.',
      'Define database schema for alerts, playbook actions, and rollback/audit logs.'
    ]
  },
  {
    number: 3,
    title: 'Environment & Data-Source Setup',
    duration: 'Wk 3',
    dates: 'Jul 27–Aug 2, 2026',
    description: 'Configure Windows auditing, Sysmon, FIM, and canary files.',
    keyTasks: [
      'Configure Windows Security Event Log auditing and deploy Microsoft Sysmon.',
      'Set up File Integrity Monitor baseline and deploy ransomware canary files across endpoints.'
    ]
  },
  {
    number: 4,
    title: 'Core Detection Engine – Rule-Based & MITRE Mapping',
    duration: 'Wk 4–5',
    dates: 'Aug 3–16, 2026',
    description: 'Build rule-based detection engine for technical threats.',
    keyTasks: [
      'Build rule-based detection for brute-force, LSASS access, PowerShell abuse, and malicious downloads.',
      'Map every detection rule directly to MITRE ATT&CK techniques.'
    ]
  },
  {
    number: 5,
    title: 'AI Module – Deepfake, Vishing & Phishing Detection',
    duration: 'Wk 6–7',
    dates: 'Aug 17–30, 2026',
    description: 'Train AI models for human-layer threat detection.',
    keyTasks: [
      'Train voice/video authenticity classifier for synthetic audio artefacts & facial anomalies.',
      'Build vishing-call scoring model and phishing URL/email classifier using NLP & domain reputation.'
    ]
  },
  {
    number: 6,
    title: 'SOAR Automation Playbook Development',
    duration: 'Wk 8–9',
    dates: 'Aug 31–Sep 13, 2026',
    description: 'Develop automated SOAR response playbooks.',
    keyTasks: [
      'Develop automated playbooks for process termination, host isolation, account lockdown, and quarantine.',
      'Extend automation to human layer: auto-block vishing calls, quarantine phishing emails.'
    ]
  },
  {
    number: 7,
    title: 'Dashboard, Alerting & System Integration',
    duration: 'Wk 10',
    dates: 'Sep 14–20, 2026',
    description: 'Build unified SOC dashboard and notification integrations.',
    keyTasks: [
      'Build unified SOC dashboard showing live alerts, MITRE mapping, and playbook status.',
      'Integrate SOC notification channels (email/SMS) for analyst approvals.'
    ]
  },
  {
    number: 8,
    title: 'Testing, Client UAT, Refinement & Deployment',
    duration: 'Wk 11',
    dates: 'Sep 21–27, 2026',
    description: 'Simulate attacks, run UAT with Swastik Chemical, and deploy.',
    keyTasks: [
      'Simulate brute-force, LSASS dumping, ransomware, and deepfake campaigns in isolated lab.',
      'Conduct UAT with Swastik Chemical staff and deploy platform into production.'
    ]
  },
];

export const GANTT_WEEKS: GanttWeek[] = [
  { weekNum: 1, dates: 'Jul 13–19', label: 'W1' },
  { weekNum: 2, dates: 'Jul 20–26', label: 'W2' },
  { weekNum: 3, dates: 'Jul 27–Aug 2', label: 'W3' },
  { weekNum: 4, dates: 'Aug 3–9', label: 'W4' },
  { weekNum: 5, dates: 'Aug 10–16', label: 'W5' },
  { weekNum: 6, dates: 'Aug 17–23', label: 'W6' },
  { weekNum: 7, dates: 'Aug 24–30', label: 'W7' },
  { weekNum: 8, dates: 'Aug 31–Sep 6', label: 'W8' },
  { weekNum: 9, dates: 'Sep 7–13', label: 'W9' },
  { weekNum: 10, dates: 'Sep 14–20', label: 'W10' },
  { weekNum: 11, dates: 'Sep 21–27', label: 'W11' },
];

export const GANTT_ACTIVITIES: GanttActivity[] = [
  { id: 'act-1', name: 'Requirement Gathering & Client Study', activeWeeks: [1] },
  { id: 'act-2', name: 'System Design & Architecture Planning', activeWeeks: [2] },
  { id: 'act-3', name: 'Environment & Data-Source Setup (Sysmon, Event Log, FIM)', activeWeeks: [3] },
  { id: 'act-4', name: 'Core Detection Engine Development (Rule-based + MITRE)', activeWeeks: [4, 5] },
  { id: 'act-5', name: 'AI Module – Deepfake, Vishing & Phishing Detection', activeWeeks: [6, 7] },
  { id: 'act-6', name: 'SOAR Automation Playbook Development', activeWeeks: [8, 9] },
  { id: 'act-7', name: 'Dashboard, Alerting & System Integration', activeWeeks: [10] },
  { id: 'act-8', name: 'Testing, Client UAT (Swastik Chemical), Refinement & Deployment', activeWeeks: [11] },
];
